### ISSUE TITLE
capistranoでamazon linuxにデプロイする際にGem Load Error is: can't create Java VMが発生する

### ISSUE THREAD

**Issue by tomohiroo** [kozo002/zipang#1]
railsプロジェクトでzipangをインストールし、capistranoでamazon linuxにデプロイする時に以下のエラーが発生しました。

```
00:08 deploy:migrate
      [deploy:migrate] Run `rake db:migrate`
00:08 deploy:migrating
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate
      01 rake aborted!
      01 Bundler::GemRequireError: There was an error while trying to load the gem 'zipang'.
      01 Gem Load Error is: can't create Java VM
      01 Backtrace for gem load error is:
      01 /home/tomohiroo/pecopeco/shared/bundle/ruby/2.5.0/gems/kuromoji-0.0.1/lib/kuromoji.rb:6:in `load'
      01 /home/tomohiroo/pecopeco/shared/bundle/ruby/2.5.0/gems/kuromoji-0.0.1/lib/kuromoji.rb:6:in `<mod…00:08 deploy:migrate
      [deploy:migrate] Run `rake db:migrate`
00:08 deploy:migrating
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate
      01 rake aborted!
      01 Bundler::GemRequireError: There was an error while trying to load the gem 'zipang'.
      01 Gem Load Error is: can't create Java VM
      01 Backtrace for gem load error is:
      01 /home/tomohiroo/pecopeco/shared/bundle/ruby/2.5.0/gems/kuromoji-0.0.1/lib/kuromoji.rb:6:in `load'
      01 /home/tomohiroo/pecopeco/shared/bundle/ruby/2.5.0/gems/kuromoji-0.0.1/lib/kuromoji.rb:6:in `<mod…00:08 deploy:migrate
      [deploy:migrate] Run `rake db:migrate`
00:08 deploy:migrating
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate
      01 rake aborted!
      01 Bundler::GemRequireError: There was an error while trying to load the gem 'zipang'.
      01 Gem Load Error is: can't create Java VM
      01 Backtrace for gem load error is:
      01 /home/tomohiroo/pecopeco/shared/bundle/ruby/2.5.0/gems/kuromoji-0.0.1/lib/kuromoji.rb:6:in `load'
      01 /home/tomohiroo/pecopeco/shared/bundle/ruby/2.5.0/gems/kuromoji-0.0.1/lib/kuromoji.rb:6:in `<mod…
```
awsのirb上でzipangをrequireすることができ、rubyのコードを動かすことはできます。
また、amazon linux上で$JAVA_HOMEは設定してあります。
ローカル環境(Mac)では正常に動作します。

環境 (リモートとローカルで一致)
```
ruby 2.5.1
rails 5.2.1
```

ローカル環境
java -version
```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```
リモート環境
java -version
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by kozo002** [comment]
@tomohiroo 
こんにちは。ご報告ありがとうございます。
zipangの依存しているkuromojiは0.0.4のはずなんですがそれが原因かもしれないですね。
0.0.1に依存している別のgemの影響ですかね?

Gemfile.lockをチェックしてもらえますか？

**Comment by tomohiroo** [comment]
ご返事ありがとうございます！
いまgemfileからzipangだけをコメントアウトするとデプロイできました。

Gemfile.lockは以下です
```GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.2.1)
      actionpack (= 5.2.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.1)
      actionpack (= 5.2.1)
      actionview (= 5.2.1)
      activejob (= 5.2.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.1)
      actionview (= 5.2.1)
      activesupport (= 5.2.1)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.2.1)
      activesupport (= 5.2.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    active_model_serializers (0.10.7)
      actionpack (>= 4.1, < 6)
      activemodel (>= 4.1, < 6)
      case_transform (>= 0.2)
      jsonapi-renderer (>= 0.1.1.beta1, < 0.3)
    activejob (5.2.1)
      activesupport (= 5.2.1)
      globalid (>= 0.3.6)
    activemodel (5.2.1)
      activesupport (= 5.2.1)
    activerecord (5.2.1)
      activemodel (= 5.2.1)
      activesupport (= 5.2.1)
      arel (>= 9.0)
    activerecord-import (0.25.0)
      activerecord (>= 3.2)
    activestorage (5.2.1)
      actionpack (= 5.2.1)
      activerecord (= 5.2.1)
      marcel (~> 0.3.1)
    activesupport (5.2.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    airbrussh (1.3.0)
      sshkit (>= 1.6.1, != 1.7.0)
    annotate (2.7.4)
      activerecord (>= 3.2, < 6.0)
      rake (>= 10.4, < 13.0)
    arel (9.0.0)
    bcrypt (3.1.12)
    binding_of_caller (0.8.0)
      debug_inspector (>= 0.0.1)
    bootsnap (1.3.2)
      msgpack (~> 1.0)
    builder (3.2.3)
    byebug (10.0.2)
    capistrano (3.11.0)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (1.3.0)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    capistrano-rails (1.4.0)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capistrano-rbenv (2.1.4)
      capistrano (~> 3.1)
      sshkit (~> 1.3)
    case_transform (0.2)
      activesupport
    coderay (1.1.2)
    concurrent-ruby (1.0.5)
    coolline (0.5.0)
      unicode_utils (~> 1.4)
    crass (1.0.4)
    debug_inspector (0.0.3)
    devise (4.5.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 6.0)
      responders
      warden (~> 1.2.3)
    diff-lcs (1.3)
    erubi (1.7.1)
    ethon (0.11.0)
      ffi (>= 1.3.0)
    factory_bot (4.11.1)
      activesupport (>= 3.0.0)
    factory_bot_rails (4.11.1)
      factory_bot (~> 4.11.1)
      railties (>= 3.0.0)
    faraday (0.15.2)
      multipart-post (>= 1.2, < 3)
    ffi (1.9.25)
    geokit (1.13.1)
    geokit-rails (2.3.1)
      geokit (~> 1.5)
      rails (>= 3.0)
    globalid (0.4.1)
      activesupport (>= 4.2.0)
    hirb (0.7.3)
    hirb-unicode (0.0.5)
      hirb (~> 0.5)
      unicode-display_width (~> 0.1.1)
    i18n (1.1.0)
      concurrent-ruby (~> 1.0)
    jsonapi-renderer (0.2.0)
    kgio (2.11.2)
    kuromoji (0.0.1)
      rjb
    kuromoji-ruby (0.0.4)
      rjb
      thor
      yajl-ruby
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.2.2)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.0)
      mini_mime (>= 0.1.1)
    marcel (0.3.2)
      mimemagic (~> 0.3.2)
    method_source (0.9.0)
    mimemagic (0.3.2)
    mini_mime (1.0.1)
    mini_portile2 (2.3.0)
    minitest (5.11.3)
    msgpack (1.2.4)
    multipart-post (2.0.0)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (5.0.2)
    newrelic_rpm (5.4.0.347)
    nio4r (2.3.1)
    nokogiri (1.8.4)
      mini_portile2 (~> 2.3.0)
    orm_adapter (0.5.0)
    pg (1.1.3)
    pry (0.11.3)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    pry-byebug (3.6.0)
      byebug (~> 10.0)
      pry (~> 0.10)
    pry-coolline (0.2.5)
      coolline (~> 0.5)
    pry-rails (0.3.6)
      pry (>= 0.10.4)
    puma (3.12.0)
    rack (2.0.5)
    rack-cors (1.0.2)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.2.1)
      actioncable (= 5.2.1)
      actionmailer (= 5.2.1)
      actionpack (= 5.2.1)
      actionview (= 5.2.1)
      activejob (= 5.2.1)
      activemodel (= 5.2.1)
      activerecord (= 5.2.1)
      activestorage (= 5.2.1)
      activesupport (= 5.2.1)
      bundler (>= 1.3.0)
      railties (= 5.2.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.4)
      loofah (~> 2.2, >= 2.2.2)
    railties (5.2.1)
      actionpack (= 5.2.1)
      activesupport (= 5.2.1)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.19.0, < 2.0)
    raindrops (0.19.0)
    rake (12.3.1)
    rb-fsevent (0.10.3)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    rjb (1.5.5)
    romaji (0.2.4)
      rake (>= 0.8.0)
    rspec-core (3.8.0)
      rspec-support (~> 3.8.0)
    rspec-expectations (3.8.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-mocks (3.8.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-rails (3.8.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.8.0)
      rspec-expectations (~> 3.8.0)
      rspec-mocks (~> 3.8.0)
      rspec-support (~> 3.8.0)
    rspec-support (3.8.0)
    ruby_dep (1.5.0)
    seed-fu (2.3.9)
      activerecord (>= 3.1)
      activesupport (>= 3.1)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-commands-rspec (1.0.4)
      spring (>= 0.9.1)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sshkit (1.17.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    thor (0.20.0)
    thread_safe (0.3.6)
    typhoeus (1.3.0)
      ethon (>= 0.9.0)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    unicode-display_width (0.1.1)
    unicode_utils (1.4.0)
    unicorn (5.4.1)
      kgio (~> 2.6)
      raindrops (~> 0.7)
    warden (1.2.7)
      rack (>= 1.0)
    websocket-driver (0.7.0)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.3)
    yajl-ruby (1.4.1)
    zipang (0.0.1)
      kuromoji
      romaji

PLATFORMS
  ruby

DEPENDENCIES
  active_model_serializers
  activerecord-import
  annotate
  binding_of_caller
  bootsnap (>= 1.1.0)
  byebug
  capistrano (~> 3.10)
  capistrano-bundler
  capistrano-rails (~> 1.4)
  capistrano-rbenv
  devise
  factory_bot_rails
  faraday
  geokit-rails
  hirb
  hirb-unicode
  kuromoji-ruby
  listen (>= 3.0.5, < 3.2)
  newrelic_rpm
  pg (>= 0.18, < 2.0)
  pry-byebug
  pry-coolline
  pry-rails
  puma (~> 3.11)
  rack-cors
  rails (~> 5.2.0)
  rjb
  romaji
  rspec-rails
  seed-fu
  spring
  spring-commands-rspec
  spring-watcher-listen (~> 2.0.0)
  typhoeus
  tzinfo-data
  unicorn
  zipang

RUBY VERSION
   ruby 2.5.1p57

BUNDLED WITH
   1.16.4
```

**Comment by tomohiroo** [comment]
kuromojiのrubygems (https://rubygems.org/gems/kuromoji) を見るとバージョンが0.0.1のようなのですが、このせいでしょうか？

**Comment by kozo002** [comment]
@tomohiroo 
Gemfile.lockの転載ありがとうございます。
バージョンの件は僕の勘違いでした、kuromoji-rubyが0.0.1でインストールされているのかと思っていました。

もしかするとデプロイ時のユーザーで$JAVA_HOMEが読めてない可能性もあるんですが、
capistranoで以下のようなtaskを適当なタイミングで走らせたときに$JAVA_HOMEの中身が出力されるか確認してみてください

```ruby
task :check_java_home do
  on roles(:app) do
    execute 'echo $JAVA_HOME'
  end
end
before 'bundler:install', 'check_java_home'
```

**Comment by tomohiroo** [comment]
確かにJAVA_HOMEがよめてないようでした。
set :default_env, {"JAVA_HOME" => "/usr/java/jdk1.8.0_181-amd64"}
をdeploy.rbに追加するとデプロイできました。

おさわがせしました。
ありがとうございます！
